use std::time::Instant;
use small_powers_of_tau::srs::Parameters;

fn main() {
    println!("Hello, wrapper-small-pot!");
    let _parameters = Parameters::new(100,2);
    contribute_with_file(
        "initialTranscript.json",
        "finalTranscript.json",
        "entropy generated by participant"
    ).unwrap();
    println!("total time: {:?}", start.elapsed());
}